### ISSUE TITLE
一些字形、編碼、設計上的建議

### ISSUE THREAD

**Issue by kujihhoe** [ichitenfont/I.Ming#48]
一點字坊的設計人員您好！非常感謝你們能開發這樣一套完整、符合規範的高質量字體。我在使用過程發現了一點小問題，
詳見我的博文 [一點明體與思源宋韓文版的比較與建議：字形篇](https://kqh.me/post/iming1/)、[一點明體與思源宋韓文版的比較與建議：設計篇](https://kqh.me/post/iming2/)。

愚見僅供參考。祝好！

**Comment by i-font** [comment]
非常感謝閣下仔細和詳盡的回饋，當中的讚賞讓我們團隊感到自豪和光榮，意見也相當精闢獨到，我們團隊也細看了良久。

當然，有部份是關於我們的理念和定位問題，容我在此解釋一下。

首先，對於Unicode分碼字，它有太多特意背離傳承字形的人爲改動，把在傳承字形取樣中字形相當統一的漢字（請留意，是同一個漢字的異寫而已，並不是「兩個不同的字」）強行區分作兩個編碼。雖其背後有當時的技術考慮，但有關技術考慮在今天已過時，站在傳承字形的角度上亦難以按其考慮作準。因此，我們基本上並不承認這些編碼區分，尤其是正體（繁體）中文裏常用的碼位，若能以傳承字形的字理和原則（在《檢校表》已詳述）貫之，則仍貫之，寧可同形，絕不摻進違背傳承字形的新字形。若我們不確立這原則，碰到「為、青」等被Unicode強分的漢字時，用戶使用「一點明體」後，滿以爲已把字形都設定作傳承字形了，豈料卻仍摻了不少新字形。這種結果，我們強烈不接受。而若把兩者互換，則輪到輸入了「爲、靑」的用戶在使用「一點明體」時會遭殃，顯示出有違傳承字形的形體。我們亦同樣不接受這種結果。

簡化字亦如上所述。像「禿」字，在《檢校表》已規定從具備字理的「儿」，不從喪失字理、因形似而訛的「几」，在不影響辨識下，仍按字理貫之。

至於用戶若有特殊需要，要顯示新字形、手寫字形或其他非傳承字形寫法時，可以用本字形的原版「IPA明體」或其他字型。這點基本上不是我們團隊處理的事情。

其次「一點明體」是協調字理與約定俗成字形間的成品，我們希望其結果是兩者兼備，當兩者眞的難分軒輊時，我們仍希望能推廣字理佔優的字形。個別字形雖若不是最常見的形體，但其字理佔優形體仍然符合我們的約定俗成測試，即在取樣中也不罕見，或者能通過十人調査，我們仍會採納。這是「一點明體」收納部份並非最常見（但亦不是罕見）形體，而最常見的則收在「一點明體異體」裏的原因。

不過，有少數字理佔優的字形，如「网罒」、「衰冄」、「尞尉」等，其實在我們團隊內亦經過多番討論。雖然我們認爲若在「一點明體」裏使用字理最佔優的寫法，未致於影響識辨，但這些寫法確實在字形設計上不容易平衡（這方面諮詢過字形設計師），也較難令人感到看起來安和適合。因此我們暫時作此安排。至於個別字形，「肅」字若依金文乃從「聿」從「𣶒」，但即使採用建議所述者作正，其「聿」部件仍欠一筆。且字理上，從「聿」者實乃從「⺕」（又，即手）持桿，持桿行於深淵，不管是憑杖陸行還是撐舟水行，都得肅然，故直接作從「肀」從「𣶒」也不違反字理。「華」字下方則是花朵盛放之象形，或連或分也不違之，故以字形設計上便於平衡者爲先。

其餘的意見，我們會再仔細考慮。希望這回覆能讓閣下理解我們的考慮。再次感謝閣下的仔細分析和精闢意見！

**Comment by Guest-615695028** [comment]
1. 補齊Unihan基本區、擴展A區。

**Comment by hfhchan** [comment]
> 補齊Unihan基本區、擴展A區；
> 抛棄與傳承印刷字形相異的手寫字形。

@Guest-615695028 閣下提出關於字集範圍的若干建議，本團隊已經收到並予以討論。本團隊亦已回覆數次，因缺乏空餘人手，暫不考慮大幅改變方針。

閣下在不同 issue 下面重覆發表相同內容，無益於解決人力資源問題。懇請閣下諒解。

**Comment by hfhchan** [comment]
「尞」「尉」和「票」一樣，小形都是從火隸變而來。目前採用與「小」同形設計，未用「小帶勾」與「小無勾」來區分。團隊需要再商議。

**Comment by hfhchan** [comment]
> Windows字體封面應顯示「Abg」而不是「繁體字」；

這個「繁體字」的字眼是 Windows 根據字體裏面宣示支援的文種而顯示。如果字體改動該屬性，以使Windows 顯示「Abg」，則在 Adobe 系列軟件中，字體會排在西文裏面，而不是和其他中文字體排在一起。

**Comment by Guest-615695028** [comment]
1. 問題是：「繁體字」的字眼會導致微軟拼音輸入法不調用該字體，而調用SimSun。
2. 增加字元U+332C（㌬）；
3. 纟讠钅饣→糹訁釒飠。

**Comment by i-font** [comment]
回應樓上：

關於第 1 點，這是微軟拼音輸入法的問題，請洽商微軟拼音輸入法的相關人員，以探求解決方法，而不是把問題轉嫁至正常的繁體字字型之上。關於第 7、8 點，因不同字型有不同授權條款，同時也有不同字面、重心等設計上的要求，並不一定可以直接套用，也許仍必須再製作。

至於那些關於簡化字及訛字問題，本組的Henry已於早前在 issue 53、56 中回應了，同時Henry亦已禮貌地敦請閣下高抬貴手，不要把已回應了的事重複再要求，因爲花在重複回答閣下的時間，就是我們團隊所失去能製作一點黑體的時間。閣下每次回覆，團隊每一個成員都會收到電郵通知。閣下繼續無理纏擾，置大腦於廢墟中，只會繼續進一步傷害我們團隊的士氣與貢獻進度。希望閣下放下這份執意，減少對我們團隊的傷害，讓我們團隊可以爭取時間集中造字型。謝天謝地！

**Comment by Guest-615695028** [comment]
收到！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ichitenfont/I.Ming"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月9日(星期四) 凌晨3:17
***@***.***&gt;;
抄送:&nbsp;"Jack ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ichitenfont/I.Ming] 一些字形、編碼、設計上的建議 (#48)





 
回應樓上：
 
關於第 1 點，這是微軟拼音輸入法的問題，請洽商微軟拼音輸入法的相關人員，以探求解決方法，而不是把問題轉嫁至正常的繁體字字型之上。關於第 7、8 點，因不同字型有不同授權條款，同時也有不同字面、重心等設計上的要求，並不一定可以直接套用，也許仍必須再製作。
 
至於那些關於簡化字及訛字問題，本組的Henry已於早前在 issue 53、56 中回應了，同時Henry亦已禮貌地敦請閣下高抬貴手，不要把已回應了的事重複再要求，因爲花在重複回答閣下的時間，就是我們團隊所失去能製作一點黑體的時間。閣下每次回覆，團隊每一個成員都會收到電郵通知。閣下繼續無理纏擾，置大腦於廢墟中，只會繼續進一步傷害我們團隊的士氣與貢獻進度。希望閣下放下這份執意，減少對我們團隊的傷害，讓我們團隊可以爭取時間集中造字型。謝天謝地！
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
