### ISSUE TITLE
Issues when setting as default fonts in MS Word

### ISSUE THREAD

**Issue by wangshicheng1225** [ichitenfont/I.Ming#75]
When setting I.Ming as the default font in Microsoft word, it may still display the input characters as the original default font (such as Dengxian).
![dengxian](https://user-images.githubusercontent.com/24318826/189322725-304d7450-d303-416e-a310-47eaaca1aa35.png)

 I found that it is because the **Windows default simplified Chinese IME** cannot recognize the input character, because the `Code Page Character Ranges` only covers `Chinese: Traditional chars` without simplified Chinese.  
![font_properties](https://user-images.githubusercontent.com/24318826/189320892-deb8fc6b-6039-47c9-bd1b-957ae3872da4.png)

I clicked the simplified Chinese, exported the modified `.ttf` file and reinstalled it. And then the simplified Chinese IME can type the characters in I.Ming font in Word. 
![click_chnsc](https://user-images.githubusercontent.com/24318826/189321249-4cd94ebf-c360-4983-beda-f965f0fa4b38.png)
![Imingdefault](https://user-images.githubusercontent.com/24318826/189322770-a30e6587-90b7-475c-9ce5-82562a0551a8.png)

I don't know whether it is suitable to support the simplified Chinese input method in future versions, via adding the simplified Chinese chars in the Code Page Range Setting, since I.Ming font itself supports simplifed Chinese chars.

I hope it can help, thanks.

**Comment by hfhchan** [comment]
I think we tried doing that before but the font ended up being displayed in the Fonts control panel with a preview that says "简体字", so we stopped doing that.

**Comment by i-font** [comment]
Thank you for your comments. We have added the Simplified Chinese code page but found a number of problems. In addition to what Henry said, when users type in Traditional Chinese, the font will automatically change back to PMingLiU（新細明體）, many users in Hong Kong and Taiwan are dissatisfied. We tried many things without success and finally had to delete the Simplified Chinese code page to get it to work. It seems that the problem is to some extent related to Windows or Word. I hope this answer helps you, thank you!
